const easyWordList = [
  { word: "dog", hint: "Man's best friend" },
  { word: "cat", hint: "Likes to chase mice" },
  { word: "sun", hint: "Provides light and warmth" },
  { word: "moon", hint: "Glowing in the night sky" },
  { word: "tree", hint: "Has branches and leaves" },
  { word: "book", hint: "Contains stories or information" },
  { word: "phone", hint: "You're probably holding one now" },
  { word: "water", hint: "Essential for life" },
  { word: "shoes", hint: "Worn on your feet" },
  { word: "pizza", hint: "A delicious round dish" },
  { word: "cloud", hint: "Fluffy in the sky" },
  { word: "car", hint: "Gets you from A to B" },
  { word: "music", hint: "A form of art with sound" },
  { word: "friend", hint: "Someone you enjoy spending time with" },
  { word: "smile", hint: "Expresses happiness" },
  { word: "sleep", hint: "Resting at night" },
  { word: "coffee", hint: "A popular morning drink" },
  { word: "game", hint: "Something you love playing" },
  { word: "work", hint: "What you do to be a successful developer" },
  { word: "beach", hint: "Sand and waves" },
  { word: "computer", hint: "What you code on" },
  { word: "chocolate", hint: "Sweet treat made from cocoa" },
  { word: "guitar", hint: "Strings and melodies" },
  { word: "hobby", hint: "Something you enjoy doing in free time" },
  { word: "money", hint: "Used for buying stuff" },
  { word: "rain", hint: "Falling from the sky on a gloomy day" },
  { word: "camera", hint: "Captures moments in a click" },
  { word: "bike", hint: "Two-wheeled transportation" },
  { word: "watch", hint: "Shows you the time" },
  { word: "garden", hint: "Plants and flowers grow here" },
  { word: "school", hint: "Place of learning" },
  { word: "fire", hint: "Produces heat and light" },
  { word: "basketball", hint: "A sport with a hoop and a ball" },
  { word: "hamburger", hint: "Delicious patty in a bun" },
  { word: "pencil", hint: "Writes on paper" },
  { word: "family", hint: "People you're related to" },
  { word: "television", hint: "Shows and movies on a screen" },
  { word: "holiday", hint: "A break from work or school" },
  { word: "mountain", hint: "Tall land formation" },
  { word: "sunset", hint: "The sun going down" },
  { word: "sleep", hint: "Resting at night" },
  { word: "beard", hint: "Facial hair on a man's face" },
  { word: "dance", hint: "Moving to the rhythm" },
  { word: "hat", hint: "Worn on your head" },
  { word: "cake", hint: "Sweet dessert for celebrations" },
  { word: "phone", hint: "You're probably holding one now" },
  { word: "flower", hint: "Blooms in a garden" },
];


const medWordList = [
  { word: "Adventure", hint: "A thrilling experience or journey." },
  { word: "Mystery", hint: "Something difficult to explain or understand." },
  { word: "Harmony", hint: "A pleasing arrangement of parts." },
  { word: "Celebrate", hint: "To acknowledge a special day or event." },
  { word: "Balance", hint: "Equal distribution of weight or harmony in different elements." },
  { word: "Whisper", hint: "Speaking very softly or quietly." },
  { word: "Journey", hint: "The act of traveling from one place to another." },
  { word: "Illuminate", hint: "To light up or make clear." },
  { word: "Infinity", hint: "An endless or limitless extent." },
  { word: "Serenade", hint: "A piece of music sung or played in the open air." },
  { word: "Delight", hint: "A high degree of gratification or pleasure." },
  { word: "Rendezvous", hint: "A meeting at an agreed time and place." },
  { word: "Radiant", hint: "Sending out light; shining or glowing brightly." },
  { word: "Tranquil", hint: "Free from disturbance or turmoil; calm." },
  { word: "Innovation", hint: "The introduction of something new." },
  { word: "Melody", hint: "A sequence of single tones that is musically satisfying." },
  { word: "Puzzle", hint: "A game or problem designed to test ingenuity." },
  { word: "Vibrant", hint: "Full of energy and enthusiasm." },
  { word: "Curiosity", hint: "A strong desire to know or learn something." },
  { word: "Enchant", hint: "To fill someone with great delight; charm." },
  { word: "Genuine", hint: "Authentic; not fake or counterfeit." },
  { word: "Infinity", hint: "An endless or limitless extent." },
  { word: "Ephemeral", hint: "Lasting for a very short time." },
  { word: "Dazzle", hint: "To impress deeply; astonish with delight." },
  { word: "Glisten", hint: "To shine with a sparkling light." },
  { word: "Ponder", hint: "To think about carefully." },
  { word: "Reverie", hint: "A state of being pleasantly lost in one's thoughts." },
  { word: "Savor", hint: "To enjoy or appreciate completely." },
  { word: "Zealous", hint: "Filled with or showing a strong and energetic desire." },
  { word: "Inquisitive", hint: "Curious or inquiring." },
  { word: "Resilient", hint: "Able to withstand or recover from difficult situations." },
  { word: "Serendipity", hint: "Finding something good without looking for it." },
  { word: "Quixotic", hint: "Extremely idealistic; unrealistic and impractical." },
  { word: "Linger", hint: "To stay in a place longer than necessary." },
  { word: "Amiable", hint: "Friendly and pleasant." },
  { word: "Glorious", hint: "Having, deserving, or bringing fame and admiration." },
  { word: "Effervescent", hint: "Bubbly and fizzy, like a sparkling drink." },
  { word: "Eloquent", hint: "Fluent or persuasive in speaking or writing." },
  { word: "Surrender", hint: "To give up control or possession." },
  { word: "Majestic", hint: "Having grandeur, beauty, or dignity." },
  { word: "Blissful", hint: "Extremely happy or joyful." },
  { word: "Symphony", hint: "A long piece of music for a full orchestra." },
  { word: "Revitalize", hint: "To give new life or vigor to." },
  { word: "Harmonize", hint: "To bring into or come into agreement or harmony." },
  { word: "Fascinate", hint: "To attract and hold the attention or interest of." },
  { word: "Reflect", hint: "To think deeply or carefully about." },
  { word: "Exquisite", hint: "Extremely beautiful and, typically, delicate." },
];


const hardWordList = [
  { word: "obfuscate", hint: "Make unclear or difficult to understand" },
  { word: "ephemeral", hint: "Lasting for a very short time" },
  { word: "plethora", hint: "An excessive amount" },
  { word: "quixotic", hint: "Extremely idealistic; unrealistic" },
  { word: "ubiquitous", hint: "Present, appearing, or found everywhere" },
  { word: "nefarious", hint: "Wicked, villainous, or criminal" },
  { word: "languish", hint: "Grow weak or feeble" },
  { word: "esoteric", hint: "Intended for or understood by only a small number of people" },
  { word: "precipitous", hint: "Dangerously high or steep" },
  { word: "vicarious", hint: "Experienced in the imagination through the feelings or actions of another person" },
  { word: "disparate", hint: "Essentially different in kind" },
  { word: "perfidious", hint: "Deceitful and untrustworthy" },
  { word: "obsequious", hint: "Obedient or attentive to an excessive or servile degree" },
  { word: "peregrinate", hint: "To travel or wander around from place to place" },
  { word: "unctuous", hint: "Excessively flattering or ingratiating" },
  { word: "quagmire", hint: "A difficult, precarious, or entrapping situation" },
  { word: "lachrymose", hint: "Tearful or given to weeping" },
  { word: "mellifluous", hint: "Sweet or musical; pleasant to hear" },
  { word: "circumlocution", hint: "The use of many words where fewer would do" },
  { word: "dissonance", hint: "Lack of harmony among musical notes" },
  { word: "ephemeral", hint: "Lasting for a very short time" },
  { word: "jejune", hint: "Lacking substance; dull" },
  { word: "nocturnal", hint: "Done, occurring, or active at night" },
  { word: "peregrination", hint: "A journey, especially a long or meandering one" },
  { word: "pulchritudinous", hint: "Beautiful in a physically attractive way" },
  { word: "recalcitrant", hint: "Resisting authority or control" },
  { word: "sesquipedalian", hint: "Characterized by long words; long-winded" },
  { word: "turpitude", hint: "Wickedness or depravity" },
  { word: "verisimilitude", hint: "The appearance of being true or real" },
  { word: "winsome", hint: "Charming in a childlike or naive way" },
  { word: "xenophobe", hint: "A person who dislikes or is prejudiced against people from other countries" },
  { word: "yaffle", hint: "To eat or drink noisily" },
  { word: "zeitgeist", hint: "The defining spirit or mood of a particular period of history" },
  { word: "anathema", hint: "Something or someone that one vehemently dislikes" },
  { word: "bucolic", hint: "Relating to the pleasant aspects of the countryside and country life" },
  { word: "cacophony", hint: "A harsh, discordant mixture of sounds" },
  { word: "disingenuous", hint: "Not candid or sincere; pretending to be unaware or unsophisticated" },
  { word: "effulgent", hint: "Shining brightly; radiant" },
  { word: "furtive", hint: "Attempting to avoid notice or attention; secretive" },
  { word: "garrulous", hint: "Excessively talkative, especially on trivial matters" },
  { word: "haphazard", hint: "Lacking any obvious principle of organization" },
  { word: "inchoate", hint: "Just begun and so not fully formed or developed" },
  { word: "juxtapose", hint: "To place or deal with close together for contrasting effect" },
  { word: "kaleidoscope", hint: "A constantly changing pattern or sequence of elements" },
  { word: "lamentation", hint: "The passionate expression of grief or sorrow" },
  { word: "magnanimous", hint: "Very generous or forgiving, especially toward a rival or someone less powerful" },
  { word: "nadir", hint: "The lowest point in the fortunes of a person or organization" },
  { word: "obstreperous", hint: "Noisy and difficult to control" },
  { word: "palliate", hint: "To make (a disease or its symptoms) less severe or unpleasant without removing the cause" },
  { word: "quandary", hint: "A state of perplexity or uncertainty over what to do in a difficult situation" },
  { word: "rhapsody", hint: "An effusively enthusiastic or ecstatic expression of feeling" },
  { word: "sycophant", hint: "A person who acts obsequiously toward someone important in order to gain advantage" },
  { word: "trepidation", hint: "A feeling of fear or agitation about something that may happen" },
  { word: "ubiquity", hint: "The state of being everywhere at once" },
  { word: "veracity", hint: "Conformity to facts; accuracy" },
  { word: "wanderlust", hint: "A strong desire to travel" },
  { word: "xanthic", hint: "Yellow or yellowish in color" },
  { word: "yeoman", hint: "A servant in a royal or noble household" },
  { word: "zealot", hint: "A person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals" }
];

